#! /bin/sh

# kill all programs
pkill sxhkd
pkill picom
pkill dunst
pkill polybar
pkill nm-applet
ps ax | grep wallpaper-rotate.sh | cut -d" " -f2 | xargs kill
ps ax | grep wallpaper-rotate.sh | cut -d" " -f3 | xargs kill

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# border color
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#fc6808"
# bspc config presel_feedback_color "'#6272a4"
bspc config focused_border_color "000"



# start programs
sxhkd &
dunst &
nm-applet &

# Wallpaper
# bash ~/dotfiles/scripts/wallpaper.sh &
# feh --bg-fill ~/Pictures/minimal/Kurz.png
bash ~/dotfiles/scripts/wallpaper-rotate.sh &

# autostart
# picom -f -D 5 -i 0.9 &
#bash ~/.config/polybar/launch.sh --cuts &
bash ~/dotfiles/.config/polybar/RealKizu/launch.sh &
bash ~/dotfiles/scripts/spotify/launchlistener.sh &

# open apps on specific workspace
bspc rule -a Firefox desktop='I'
bspc rule -a discord desktop='IV'
bspc rule -a Spotify desktop='V'
bspc rule -a org.gnome.Nautilus desktop='VI'