#! /bin/sh

# kill all programs
pkill sxhkd
pkill picom
pkill dunst
pkill polybar
pkill nm-applet

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# border color
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#bd93f9"
# bspc config focused_border_color "#fc6808"
# bspc config presel_feedback_color "'#6272a4"
bspc config focused_border_color "000"



# start programs
sxhkd &
dunst &
nm-applet &

# Wallpaper
feh --bg-fill Pictures/Wallpapers/iamroot.jpg
#fish random 1 10 | xargs -I{rn} feh --bg-fill Pictures/Wallpapers/{rn}.jpg

# autostart
# picom -f -D 5 -i 0.9 &
#bash ~/.config/polybar/launch.sh --cuts &
bash ~/.config/polybar/RealKizu/launch.sh &
bash ~/scripts/spotify/launchlistener.sh &

